import json

with open('compare_cumulative_regret.ipynb', 'r') as f:
    nb = json.load(f)

new_cell = {
 "cell_type": "code",
 "execution_count": None,
 "metadata": {},
 "outputs": [],
 "source": [
  "# ---- Running Minimum vs Iterations ----\n",
  "import numpy as np\n",
  "import matplotlib.pyplot as plt\n",
  "import torch\n",
  "import os\n",
  "\n",
  "fig, ax = plt.subplots(figsize=(14, 9))\n",
  "\n",
  "linestyle_map = {\n",
  "    0.1**2: '-',    # solid  for sigma=0.1\n",
  "    0.2**2: '--',   # dashed for sigma=0.2\n",
  "}\n",
  "\n",
  "for noise in noise_levels:\n",
  "    noise_str = str(noise)\n",
  "    sigma = np.sqrt(noise)\n",
  "    ls = linestyle_map[noise]\n",
  "\n",
  "    for mname, cfg in methods.items():\n",
  "        all_runmins = []\n",
  "        min_len = MAX_BUDGET\n",
  "        \n",
  "        for trial in run_list:\n",
  "            fpath = os.path.join(cfg['dir'],\n",
  "                                 cfg['pattern'].format(noise=noise_str, trial=trial))\n",
  "            if not os.path.exists(fpath):\n",
  "                continue\n",
  "\n",
  "            try:\n",
  "                data = torch.load(fpath, map_location=device, weights_only=False)\n",
  "                true_response = data['true_response'].to(torch.float32).to(device)\n",
  "                num_of_queries = data['queries']\n",
  "                \n",
  "                vals = true_response.detach().cpu().numpy().reshape(-1)\n",
  "                track = num_of_queries.detach().cpu().numpy().astype(np.int32).reshape(-1)\n",
  "                \n",
  "                expanded_vals = []\n",
  "                for i in range(len(vals)):\n",
  "                    expanded_vals += list(np.repeat(vals[i], track[i]))\n",
  "                expanded_vals = np.array(expanded_vals)\n",
  "                \n",
  "                runmin = np.minimum.accumulate(expanded_vals)\n",
  "                min_len = min(min_len, len(runmin))\n",
  "                all_runmins.append(runmin)\n",
  "            except Exception as exc:\n",
  "                print(f\"[WARN] {fpath}: {exc}\")\n",
  "\n",
  "        if all_runmins:\n",
  "            all_runmins = [a[:min_len] for a in all_runmins]\n",
  "            arr = np.array(all_runmins)\n",
  "            mean = arr.mean(axis=0)\n",
  "            stderr = arr.std(axis=0) / np.sqrt(len(all_runmins))\n",
  "            \n",
  "            end = min(min_len, X_LIM)\n",
  "            iters = np.arange(1, end + 1)\n",
  "            \n",
  "            color = cfg['colors'][noise]\n",
  "            ax.fill_between(iters, mean[:end] - stderr[:end], mean[:end] + stderr[:end],\n",
  "                            alpha=0.15, color=color)\n",
  "            ax.plot(iters, mean[:end], label=f\"{mname} ($\\\\sigma={sigma:.1f}$)\", color=color, \n",
  "                    linestyle=ls, linewidth=2, marker=cfg['marker'], markevery=500)\n",
  "\n",
  "ax.axhline(f_max, color='grey', linestyle='--', linewidth=1.5,\n",
  "           label=f'Global opt = {f_max:.4f}')\n",
  "\n",
  "ax.legend(prop={'size': 14}, loc='upper right')\n",
  "ax.set_xlim([0, X_LIM])\n",
  "ax.set_ylim([0.0, 0.2])\n",
  "ax.set_xlabel('Iterations', fontsize=16)\n",
  "ax.set_ylabel('Running Minimum MAE [in]', fontsize=16)\n",
  "ax.set_title('Running Minimum MAE vs Iterations\\n(solid $\\\\sigma=0.1$, dashed $\\\\sigma=0.2$)', fontsize=18)\n",
  "ax.grid(True, alpha=0.3)\n",
  "ax.tick_params(labelsize=13)\n",
  "\n",
  "plt.tight_layout()\n",
  "plt.savefig('running_minimum_comparison.png', dpi=600, bbox_inches='tight')\n",
  "plt.show()\n",
  "print('Saved running_minimum_comparison.png')\n"
 ]
}

nb['cells'].append(new_cell)

with open('compare_cumulative_regret.ipynb', 'w') as f:
    json.dump(nb, f, indent=1)

